### ISSUE TITLE
Suggestion to implement `async_get` on future/shared_future

### ISSUE THREAD

**Issue by marack** [ashtum/saf#1]
It seems like being able to perform the asynchronous wait and the get operation in one line would make for simpler user code.  For example:

```C++
// current code
co_await future.async_wait();
auto value = future.get();

// but why not this?
auto value = co_await future.async_get();
```

Just wondering if there is a reason that combining these operations into a single call might be problematic?  

Thanks for the library!

**Comment by ashtum** [comment]
There are a few reasons for that decision, which are not immediately obvious when working with C++20 coroutines:

If we use `co_await future.async_get();`, the completion handler signature must be `void(std::exception_ptr, T)`. This implies that `T` must be DefaultConstructible, as the handler needs to be invoked on errors when no value is available. This adds another restriction: `T` must also be Movable.

Another issue with `void(std::exception_ptr, T)` is that it doesn't work well in cases where error codes need to be propagated to higher layers.

By the way, it's still possible to add an `async_get` interface alongside the existing one, allowing users to choose which to use. In many cases, `T` might meet the requirements, and users may not be concerned with handling exceptions.

**Comment by ashtum** [comment]
I've added the `future::async_extract` interface, which moves the value out of the future and passes it to the completion handler. You can use it like this:

```C++
std::cout << co_await future.async_extract() << '\n';
```
